# Generated by Django 5.0.6 on 2026-05-16 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, verbose_name='Fecha y hora')),
                ('tipo', models.CharField(db_index=True, max_length=64, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('info', 'Informativa'), ('aviso', 'Aviso'), ('critico', 'Critica')], default='info', max_length=10, verbose_name='Nivel')),
                ('variable', models.CharField(max_length=64, verbose_name='Variable')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('recomendacion', models.TextField(blank=True, default='', verbose_name='Recomendacion')),
                ('revisada', models.BooleanField(default=False, verbose_name='Revisada')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_hora', '-nivel'],
            },
        ),
        migrations.CreateModel(
            name='EnviroProRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, unique=True, verbose_name='Fecha y hora')),
                ('humedad_media', models.FloatField(blank=True, null=True, verbose_name='Humedad media (%)')),
                ('humedad_min', models.FloatField(blank=True, null=True, verbose_name='Humedad min (%)')),
                ('humedad_max', models.FloatField(blank=True, null=True, verbose_name='Humedad max (%)')),
                ('temp_suelo_media', models.FloatField(blank=True, null=True, verbose_name='Temperatura media (C)')),
                ('temp_suelo_max', models.FloatField(blank=True, null=True, verbose_name='Temperatura max (C)')),
                ('temp_suelo_min', models.FloatField(blank=True, null=True, verbose_name='Temperatura min (C)')),
                ('bateria_v', models.FloatField(blank=True, null=True, verbose_name='Bateria (V)')),
                ('panel_solar_v', models.FloatField(blank=True, null=True, verbose_name='Panel solar (V)')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Lectura EnviroPro',
                'verbose_name_plural': 'Lecturas EnviroPro',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('descartada', 'Descartada')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('alerta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='enviropro.alert', verbose_name='Alerta relacionada')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
